FORMAT: 1A
HOST: http://elixre.uk

# Elixre API

API used by the Elixre regualar expression tester/editor.


# Group Regex


## Regex [/regex]

### Perform Regex [POST]

Takes a regex with a pattern, modifiers, and subjects, and returns the result
of applying the pattern to the subject, if possible.

`Regex.scan/3` is used, so all matches inside the subjects will be returned,
rather then just the first.


+ Request (application/json)

    + Body

            {
              "regex": {
                "pattern": "foo",
                "modifiers": "iu",
                "subjects": [
                  "foobarfoo",
                  "FOOBAR",
                  "barfoo",
                ],
              }
            }

+ Response 200

    A successful request with a valid regex.

    + Body

            {
              "regex": {
                "pattern": "^foo",
                "modifiers": "iu",
                "valid_regex": true,
                "results": [
                  {
                    "subject": "foobar",
                    "binaries": ["foo"],
                    "indexes": [[0, 3]]
                  },
                  {
                    "subject": "FOOBAR",
                    "binaries": ["FOO"],
                    "indexes": [[0, 3]]
                  },
                  {
                    "subject": "barfoo",
                    "binaries": [],
                    "indexes": []
                  }
                ]
              }
            }


+ Response 200

    A successful request with an invalid regex which could not be compiled.

    The `errors` field contains the regex compilation errors passed back from
    the Elixre `Regex` module.

    + Body

            {
              "regex": {
                "pattern": "?",
                "modifiers": "iu",
                "valid_regex": false,
                "errors": [
                  [
                    "nothing to repeat",
                    0
                  ]
                ]
              }
            }


+ Response 401

    An Unsuccessful request due to one or more missing parameters.

    + Body

            {
              "errors": {
                "missing_params": [
                  "pattern"
                ]
              }
            }
